### ISSUE TITLE
Consecutives \t are not handled correctly

### ISSUE THREAD

**Issue by matteosaporiti** [TypesettingCartel/Aegisub-Motion#19]
If I try to apply a motion tracking to something like

    {\blur10\t(0,600,\blur7)\t(600,1000,0.5,\blur3)\t(1000,3000,0.65,\blur0.6)}
the result comes out wrong, because \t is always handled like is starting from the "static" value and not from the end of the previous \t.
This means that when motion tracked the type goes like:
blur10->blur7 | blur10->blur->3 | blur10->blur0.6

**Comment by torque** [comment]
This is a known problem with the transform interpolation. This line should be handled properly if you turn off the `Interp. transforms` option. This will be fixed at some point before 1.0.0 final.

Going to leave the issue open as a reminder. Thanks.

**Comment by torque** [comment]
Closing as fixed with beta 4. Feel free to reopen if you encounter problems with the fix.
