### ISSUE TITLE
Lua error when applying

### ISSUE THREAD

**Issue by alucryd** [TypesettingCartel/Aegisub-Motion#22]
Hi,

Having just heard of your awesome tool I gave it a spin, but every time I select apply I run into this error:

Lua reported a runtime error:
    File "/home/alucryd/.aegisub/automation/autoload/Aegisub-Motion.moon", line 347
<anonymous function at lines 324-449>
    File "/home/alucryd/.aegisub/automation/include/a-mo/DataWrapper.moon", line 33
bestEffortParsingAttempt
attempt to index local 'input' (a nil value)

I tried v1.0.0-beta2 with aegisub 3.2.2 and its latest git on Arch Linux, both gave me the same error. After reading about issue #10 I also tried deleting ~/.aegisub/aegisub-motion.json but it didn't help. Any idea where it might be coming from?

**Comment by line0** [comment]
try the following: after [this line](https://github.com/TypesettingCartel/Aegisub-Motion/blob/master/Aegisub-Motion.moon#L110), insert the following (outside the if block):
````lua
return ""
````

**Comment by torque** [comment]
That's a bad oversight. Thanks for finding it.

I disabled the clipboard module on Linux because lachs0r kept complaining about it crashing Aegisub on Linux. I wonder if he is a special case or if it really does have problems.

**Comment by torque** [comment]
Should be fixed in [1.0.0-beta3](https://github.com/TypesettingCartel/Aegisub-Motion/releases/tag/v1.0.0-beta3). Let me know if it isn't.

**Comment by alucryd** [comment]
Thx for the lightning-fast answers guys. I just tried 1.0.0-beta3, but now aegisub simply refuses to load the script at launch:

12:06:52 PM: A script in the Automation autoload directory failed to load.
Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
12:06:52 PM: Failed to load Automation script '/home/alucryd/.aegisub/automation/autoload/Aegisub-Motion.moon':
Error initialising Lua script "Aegisub-Motion.moon":

[string "/home/alucryd/.aegisub/automation/include/a-m..."]:3: module 'a-mo.log' not found:
	no field package.preload['a-mo.log']
	no file './a-mo/log.so'
	no file '/usr/local/lib/lua/5.1/a-mo/log.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './a-mo.so'
	no file '/usr/local/lib/lua/5.1/a-mo.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by torque** [comment]
ugh, case sensitive filesystem bug. I'm getting sloppy. Rename `include/a-mo/Log.moon` to `include/a-mo/log.moon`, and it should fix that problem.

**Comment by alucryd** [comment]
Works like a charm, thx a lot!
