### ISSUE TITLE
Support for karaoke effects

### ISSUE THREAD

**Issue by occivink** [TypesettingCartel/Aegisub-Motion#23]
At the moment, karaoke'd lines are not properly handled. The lines generated all have the same karaoke markers as the original line, effectively overriding the karaoke effect.

Ideally, they should be updated in a similar way to the \fade tag, with each marker being offset depending on the frame, to preserve the original karaoke effect.

**Comment by torque** [comment]
I'd (surprisingly?) never received a request for this before, but it shouldn't be too hard to add.

**Comment by torque** [comment]
Closing as fixed with the release of beta 4.  Feel free to reopen if you have problems.

**Comment by occivink** [comment]
I greatly appreciate how promptly you worked on this and the fix works very well for \k and \ko tags, however it does not behave properly for \kf tags. Decrementing the duration does not offset the starting point, which is what you'd want. You can easily notice this if you have a line covered by a single \kf tag on which you apply tracking data. 

From what I've seen, instead of decrementing the tag value by the offset, adding an additional \kf tag before with the negative offset gives the intended behaviour. For example this
{\kf56} => {\kf52}
doesn't work, but
{\kf56} => {\kf-4\kf56}
does.

Another small issue is that when a tag gets decremented to 0, it leaves trailing empty braces. However, this is easily cleaned up.

Thank you for your work.

**Comment by torque** [comment]
Shifting `\kf` should be fixed as of 761cf4dea2755014ff0aaa0c1c1238e0d6abf22d. Thanks for the description of the behavior and solution.

Also added removal of empty braces in 7cc6f9781d79a62cd89f86843e054e9b81c03be3.

Re: reopening the issue, there is a "Reopen and comment" button for me, but maybe that's because I'm the owner of the repository.

**Comment by occivink** [comment]
This works nicely, thank you very much!
