### ISSUE TITLE
Ctrl+A functionality addition

### ISSUE THREAD

**Issue by user1234567891011** [TypesettingCartel/Aegisub-Motion#24]
It would be a great time saver when replacing the data/file location in the input field, to be able to use Ctrl+A to select all the text instead of having to right-click > select all and then subsiquently delete it.

**Comment by torque** [comment]
Looks like the only thing stopping it from working was the abort button accelerator overriding the text box's default behavior. Will fix this after I make sure it works on Windows.

**Comment by user1234567891011** [comment]
Sounds good and simple enough. Many thanks. 

P.s. Sorry for the off topic question, but are you still available on IRC? torque on freenode and rizon? I have connected to both, it seems like the freenode one is more "active" than rizon

**Comment by torque** [comment]
Hmm, disabling the button accelerator did not fix the problem on Windows like it did on OSX, so I'm going to have to chalk this up to being Aegisub's fault rather than mine. Will still shuffle the accelerators around, though.

And yes, I'm still on irc on both networks.
