### ISSUE TITLE
Line length not calculated from motion data (nil)

### ISSUE THREAD

**Issue by user1234567891011** [TypesettingCartel/Aegisub-Motion#26]
If I understand this correctly, Aegisub-motion does not calculate the number of lines the exported motion data takes up and reports it as being (nil):

![apply motion error](https://cloud.githubusercontent.com/assets/11341653/6566618/cc900f66-c720-11e4-81b7-a07de6b9871d.PNG)
 
Using r8700 build of Aegisub and v1.0.0 beta 5 of Aegisub-Motion.

**Comment by torque** [comment]
Thanks for reporting this bug.

**Comment by user1234567891011** [comment]
Not a problem. Thank you for the fix.
